---
- name: Test code to display variables
  hosts: "{{ groups[hg_all][1] }}"
  gather_facts: no
  become: false

  tasks:
    - block:
      - name: trimming first 3 characters
        set_fact:
          searchname: "RS_{{ cluster[-3:]|upper }}_{{ sharetype|replace(' ','') }}*"
      - name: display variable
        debug:
          msg: "{{ searchname }}"
      - name: current share number increment by 1
        set_fact:
          currentshareno: "{{ cluster[-3:] | int + 1 }}"
      - name: convert to 3 digit
        set_fact:
          shareno: "{{ \"%03d\" | format(currentshareno | int) }}"
      - name: display variable
        debug:
          msg: "{{ shareno }}"
      - name: cat test.txt
        command: 
          cat /tmp/test.txt
        register: new_var
      - name: trim new_var
        shell:
          echo "{{ new_var.stdout }}" | awk /./ | awk '{print $2}' | grep -E '[0-9]' | sort | tail -1
        register: fetchedshare
      - name: display variable
        debug:
          msg: "{{ fetchedshare.stdout }}"
        ignore_errors: true
      rescue:
        - name: display message
          debug:
            msg: "this is rescue block for anyserver"
