---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: yes
  become_user: root

  tasks:
    - name: ping cluster
      command:
        ping -c1 "{{ cluster }}"
      register: cluster_ping
      ignore_errors: yes
