---
- name: Test code to display variables
  hosts: "{{ groups[hg_all][1] }}"
  gather_facts: no
  become: false

  tasks:
    - block:
      - name: trimming first 3 characters
        set_fact:
          searchname: "RS_{{ cluster[-3:]|upper }}_{{ sharetype|replace(' ','') }}*"
      - name: display variable
        debug:
          msg: "{{ searchname }}"
      - name: increment by 1
          set_fact:
            sharename: "RS_{{ cluster[0:3]|upper }}_{{ sharetype|replace(' ','') }}{{ cluster[-3:0] | int + 1 }}"
      - name: display variable
        debug:
          msg: "{{ sharename }}"
      - name: ping cluster
        command: 
          /usr/bin/ping -c 1 tower1
        register: new_var
        ignore_errors: true
      - name: fail the task if server is not pinging
        fail:
          msg: "please check google.com"
        when: (new_var is success) == false
      - name: ping google
        command: 
          /usr/bin/ping -c 1 google.com
        register: new_var1
      - name: display new_var
        debug:
          msg: "google.com is pinging"
        when: (new_var1 is success) == True
      rescue:
        - name: display message
          debug:
            msg: "this is rescue block for anyserver"
