---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: true

  tasks:
    - name: ping cluster
      local_action: command ping -c 1 {{ cluster }}
      register: cluster_ping
