---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - command:
        ping -c1 "{{ cluster }}"
      register: cluster_ping
      ignore_error: yes
