---
- name: Test code to display variables
  hosts: "{{ groups[hg_all][0] }}"
  gather_facts: no
  become: false

  tasks:
    - block:
      - name: cat test.txt
        command: 
          cat /tmp/test.txt
        register: new_var
      - name: display variable
        debug:
          msg: "{{ new_var.stdout }}"
      rescue:
        - name: display message
          debug:
            msg: "this is rescue block for anyserver"
