---
- name: Test code to display variables
  hosts: "{{ groups[hg_all][1] }}"
  gather_facts: no
  become: false

  tasks:
    - name: ping cluster
      command:
        which ping
      register: cluster_ping
    - name: ping cluster
      command:
        whoami
      register: cluster_ping
    - name: ping cluster
      command:
        hostname
      register: cluster_ping
    - name: ping cluster
      command: 
        /usr/bin/ping -c 1 anyserver
      register: new_var
    - name: display new_var
      debug:
        msg: "please check anyserver"
      when: (new_var is success) = false
    - name: ping google
      command: 
        /usr/bin/ping -c 1 google.com
      register: new_var1
    - name: display new_var
      debug:
        msg: "google.com is pinging"
      when: (new_var1 is success) = True
