---
- name: Test code to display variables
  hosts: "{{ groups[hg_all][0] }}"
  gather_facts: no
  become: false

  tasks:
    - block:
      - name: display extra variables
        debug:
          msg: "{{ cluster }} -  {{ svm }} - {{ sharetype }} - {{ sharesize }}"
      rescue:
        - name: display message
          debug:
            msg: "this is rescue block for anyserver"
