---
- name: Test code to display variables
  hosts: "{{ groups[hg_all][0] }}"
  gather_facts: no
  become: false

  tasks:
    - block:
      - name: cat test.txt
        command: 
          cat /tmp/test.txt
        register: new_var
      - name: display variable
        debug:
          msg: "{{ new_var.stdout }}"
      - name: parsing xml output
        xml:
          xmlstring: "{{ new_var.stdout }}"
          namespaces:
            ns: http://www.netapp.com/filer/admin
          xpath: "/ns:results/ns:cli-output"
          content: 'text'
        register: clioutput
      - name: display variable
        debug:
          msg: "{{ clioutput.matches.http://www.netapp.com/filer/admin.cli-output }}"
      rescue:
        - name: display message
          debug:
            msg: "this is rescue block for anyserver"
