---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: false

  tasks:
    - name: ping cluster
      command:
        /usr/sbin/ping -c1 "{{ cluster }}"
      register: cluster_ping
      ignore_errors: yes
