---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: false

  tasks:
    - name: ping cluster
      command:
        ping -c 1 {{ cluster }}
      register: cluster_ping
