---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: false

  tasks:
    - name: ping cluster
      command:
        hostname
      register: cluster_ping
      ignore_errors: yes
