---
- name: Test code to display variables
  hosts: "{{ hg_local }}"
  gather_facts: no
  become: false

  tasks:
    - name: ping cluster
      command:
        which ping
      register: cluster_ping
    - name: ping cluster
      command:
        whoami
      register: cluster_ping
    - name: ping cluster
      command:
        hostname
      register: cluster_ping
    - name: ping cluster
      local_action:
        command: /usr/bin/ping -c 1 "{{ groups[hg_all][0] }}"
        register: cluster_ping
