---
- name: Test code to display variables
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: display extra vars
      debug:
        msg: "{{ cluster }} - {{ svm }} - {{ sharetype }}"
